### ISSUE TITLE
Be more friendly to JS devs

### ISSUE THREAD

**Issue by gucong3000** [bellingard/sonar-scanner-npm#27]
- [ ] Add usage for cli user
  - [ ] extract report info from package.json #25
  - [ ] Update sonar.exclusions #24
  - [ ] Update parameter of API & CLI #23
  - [ ] analysis this module using npm scripts:

**Comment by bellingard** [comment]
Hi @gucong3000, just a quick message to tell you that I appreciate your contribution and that I'll be reviewing your PRs soon - I'm just running out of time currently.

**Comment by gucong3000** [comment]
Related:
- stylelint/stylelint#2880

**Comment by davidkarlsen** [comment]
Also extract version from package.json - that does not seem to happen for me (running the command line version).

**Comment by trajano** [comment]
can `/www` also be excluded for cordova applications?
